version: '3.8'

services:
  auth:
    build:
      context: ./services/auth
    env_file:
      - .env.development
    ports:
      - "${AUTH_SERVICE_PORT}:8000"
    networks:
      - microservices

  product:
    build:
      context: ./services/product
    env_file:
      - .env.development
    ports:
      - "${PRODUCT_SERVICE_PORT}:8000"
    networks:
      - microservices

  cart:
    build:
      context: ./services/cart
    environment:
      - AUTH_SERVICE_HOST=auth
    env_file:
      - .env.development
    ports:
      - "${CART_SERVICE_PORT}:8000"
    networks:
      - microservices

networks:
  microservices: