version: '3.8'

services:
  auth:
    build:
      context: ./services/auth
    env_file:
      - .env.development
    ports:
      - "${AUTH_SERVICE_PORT}:50051"
    networks:
      - microservices

  product:
    build:
      context: ./services/product
    env_file:
      - .env.development
    ports:
      - "${PRODUCT_SERVICE_PORT}:50052"
    networks:
      - microservices

  cart:
    build:
      context: ./services/cart
    environment:
      - AUTH_SERVICE_HOST=auth
      - PRODUCT_SERVICE_HOST=product
      - AUTH_SERVICE_PORT=50051
      - PYTHONUNBUFFERED=1  # Обеспечивает немедленный вывод логов

    env_file:
      - .env.development
    ports:
      - "${CART_SERVICE_PORT}:50053"
    networks:
      - microservices

networks:
  microservices:
