# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_proto.product.product_pb2 as product__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in product_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class ProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Categories = channel.unary_unary(
            "/product.Product/Categories",
            request_serializer=product__pb2.CategoryRequest.SerializeToString,
            response_deserializer=product__pb2.CategoryResponse.FromString,
            _registered_method=True,
        )
        self.CreateCategory = channel.unary_unary(
            "/product.Product/CreateCategory",
            request_serializer=product__pb2.CreateCategoryRequest.SerializeToString,
            response_deserializer=product__pb2.CreateCategoryResponse.FromString,
            _registered_method=True,
        )
        self.ProductsByCategory = channel.unary_unary(
            "/product.Product/ProductsByCategory",
            request_serializer=product__pb2.ProductsByCategoryRequest.SerializeToString,
            response_deserializer=product__pb2.ProductsByCategoryResponse.FromString,
            _registered_method=True,
        )
        self.GetProduct = channel.unary_unary(
            "/product.Product/GetProduct",
            request_serializer=product__pb2.ProductRequest.SerializeToString,
            response_deserializer=product__pb2.ProductResponse.FromString,
            _registered_method=True,
        )


class ProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Categories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateCategory(self, request, context):
        """rpc UpdateCategory(UpdateCategoryRequest) returns (UpdateCategoryResponse);
        rpc DeleteCategory(DeleteCategoryRequest) returns (DeleteCategoryResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProductsByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Categories": grpc.unary_unary_rpc_method_handler(
            servicer.Categories,
            request_deserializer=product__pb2.CategoryRequest.FromString,
            response_serializer=product__pb2.CategoryResponse.SerializeToString,
        ),
        "CreateCategory": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCategory,
            request_deserializer=product__pb2.CreateCategoryRequest.FromString,
            response_serializer=product__pb2.CreateCategoryResponse.SerializeToString,
        ),
        "ProductsByCategory": grpc.unary_unary_rpc_method_handler(
            servicer.ProductsByCategory,
            request_deserializer=product__pb2.ProductsByCategoryRequest.FromString,
            response_serializer=product__pb2.ProductsByCategoryResponse.SerializeToString,
        ),
        "GetProduct": grpc.unary_unary_rpc_method_handler(
            servicer.GetProduct,
            request_deserializer=product__pb2.ProductRequest.FromString,
            response_serializer=product__pb2.ProductResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "product.Product", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("product.Product", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Product(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Categories(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.Product/Categories",
            product__pb2.CategoryRequest.SerializeToString,
            product__pb2.CategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateCategory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.Product/CreateCategory",
            product__pb2.CreateCategoryRequest.SerializeToString,
            product__pb2.CreateCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ProductsByCategory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.Product/ProductsByCategory",
            product__pb2.ProductsByCategoryRequest.SerializeToString,
            product__pb2.ProductsByCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProduct(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/product.Product/GetProduct",
            product__pb2.ProductRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
