# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_proto.cart.cart_pb2 as cart__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in cart_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class CartStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCart = channel.unary_unary(
            "/cart.Cart/GetCart",
            request_serializer=cart__pb2.GetCartRequest.SerializeToString,
            response_deserializer=cart__pb2.GetCartResponse.FromString,
            _registered_method=True,
        )
        self.AddToCart = channel.unary_unary(
            "/cart.Cart/AddToCart",
            request_serializer=cart__pb2.AddToCartRequest.SerializeToString,
            response_deserializer=cart__pb2.AddToCartResponse.FromString,
            _registered_method=True,
        )
        self.DeleteFromCart = channel.unary_unary(
            "/cart.Cart/DeleteFromCart",
            request_serializer=cart__pb2.DeleteFromCartRequest.SerializeToString,
            response_deserializer=cart__pb2.DeleteFromCartResponse.FromString,
            _registered_method=True,
        )
        self.ClearCart = channel.unary_unary(
            "/cart.Cart/ClearCart",
            request_serializer=cart__pb2.ClearCartRequest.SerializeToString,
            response_deserializer=cart__pb2.ClearCartResponse.FromString,
            _registered_method=True,
        )
        self.UpdateCart = channel.unary_unary(
            "/cart.Cart/UpdateCart",
            request_serializer=cart__pb2.UpdateCartRequest.SerializeToString,
            response_deserializer=cart__pb2.UpdateCartResponse.FromString,
            _registered_method=True,
        )


class CartServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CartServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetCart": grpc.unary_unary_rpc_method_handler(
            servicer.GetCart,
            request_deserializer=cart__pb2.GetCartRequest.FromString,
            response_serializer=cart__pb2.GetCartResponse.SerializeToString,
        ),
        "AddToCart": grpc.unary_unary_rpc_method_handler(
            servicer.AddToCart,
            request_deserializer=cart__pb2.AddToCartRequest.FromString,
            response_serializer=cart__pb2.AddToCartResponse.SerializeToString,
        ),
        "DeleteFromCart": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFromCart,
            request_deserializer=cart__pb2.DeleteFromCartRequest.FromString,
            response_serializer=cart__pb2.DeleteFromCartResponse.SerializeToString,
        ),
        "ClearCart": grpc.unary_unary_rpc_method_handler(
            servicer.ClearCart,
            request_deserializer=cart__pb2.ClearCartRequest.FromString,
            response_serializer=cart__pb2.ClearCartResponse.SerializeToString,
        ),
        "UpdateCart": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateCart,
            request_deserializer=cart__pb2.UpdateCartRequest.FromString,
            response_serializer=cart__pb2.UpdateCartResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cart.Cart", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("cart.Cart", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Cart(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.Cart/GetCart",
            cart__pb2.GetCartRequest.SerializeToString,
            cart__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddToCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.Cart/AddToCart",
            cart__pb2.AddToCartRequest.SerializeToString,
            cart__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteFromCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.Cart/DeleteFromCart",
            cart__pb2.DeleteFromCartRequest.SerializeToString,
            cart__pb2.DeleteFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.Cart/ClearCart",
            cart__pb2.ClearCartRequest.SerializeToString,
            cart__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.Cart/UpdateCart",
            cart__pb2.UpdateCartRequest.SerializeToString,
            cart__pb2.UpdateCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
